var texts = [
"index",
"about",
"database",
"radio",
"tv",
"shadow",
"condensation",
"imagination",
"calculation",
"creativity",
"reproductive",
"solution",
"balance",
"gravity",
"digestion",
"memorization",
"xml",
];var tc = TagCloud('.content', texts);console.log(tc);