"en/playlist",
"en/tv",
"en/edit",
"en/delete",
"en/chatbot",
"en/tagcloud",
"en/articles",
"en/dictionary",
"en/reviews",
"en/elizabot",
"en/index",
];var tc = TagCloud('.content', texts);console.log(tc);